### PR TITLE
Reformat FB embed markup

### PR DESCRIPTION
**Pull request by dashaluna**

### CODE REVIEW

**Comment by dashaluna** [comment]
@mattheu hm.. I'm a bit confused if [FB embedded post format](https://developers.facebook.com/docs/plugins/embedded-posts) is ok for all FB embeds or only specific kind?

**Comment by dashaluna** [comment]
@mattheu PS worked for me for video and person's post embed, so I'm guessing it's ok for all, but wanted to double check with you.

**Comment by mattheu** [comment]
Lets try this

**Comment by dashaluna** [comment]
:+1:

**Pull request merged**
